# Generated by Django 3.0.7 on 2020-11-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=120)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=55, verbose_name="Student's Name")),
                ('StudentMobile', models.IntegerField(verbose_name="Student's Mobile")),
                ('StudentEmail', models.EmailField(max_length=254, verbose_name="Student's Email")),
                ('Qualification', models.CharField(max_length=55, verbose_name='Highest Qualification')),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='MALE', max_length=20)),
                ('FatherName', models.CharField(max_length=55, verbose_name="Father's Name")),
                ('FatherMobile', models.IntegerField(verbose_name="Father's Mobile")),
                ('CourseChoice', models.CharField(choices=[('Programming Language', 'Programming Language'), ('Web Development', 'Web Development'), ('Ethical Hacking', 'Ethical Hacking'), ('Digital Marketing', 'Digital Marketing'), ('Networking & CCNA', 'Networking & CCNA'), ('Cloud Computing', 'Cloud Computing'), ('Graphic Designing', 'Graphic Designing'), ('Basic Computer', 'Basic Computer')], default='--Select a Course--', max_length=55, verbose_name='Select a Course')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEnq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientName', models.CharField(max_length=55, verbose_name='Name')),
                ('Mobile', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('WorkingOrganization', models.CharField(max_length=55)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='MALE', max_length=20)),
                ('ServiceChoice', models.CharField(choices=[('Corporate Training', 'Corporate Training'), ('Workshop & Seminar', 'Workshop & Seminar'), ('Web Developement', 'Web Developement'), ('Digital Marketing', 'Digital Marketing'), ('Hardware & Networking', 'Hardware & Networking'), ('Accounting Service', 'Accounting Service'), ('Graphic Designing', 'Graphic Designing')], default='--Select a Service--', max_length=55, verbose_name='Select a Service')),
            ],
        ),
    ]
